### ISSUE TITLE
No module named file_operation error!

### ISSUE THREAD

**Issue by giangnguyen2412** [ucasir/NPRF#6]
Dear authors,

Thank you for such a great paper and code sharing. I am running a command to train model following your instruction in README.MD but I am facing this error. I am supposing it comes from a custom library from you. 

![Screenshot from 2019-05-15 03-29-25](https://user-images.githubusercontent.com/30857111/57756763-f0122f00-76c1-11e9-8f5c-cd3009e8d912.png)

Could you please check it for fixing problem. 

Thank you.

**Comment by canjiali** [comment]
Hi, the "file_operation.py" is right on the "utils" folder. You should enter the "model" folder then run "python nprf_drmm.py ...".
 The reason for this error is that we add a system path by "sys.path.append("../utils")" in MODEL.py, which help the system to find out where "file_operation" is. This can be revised in a more elegant way in the future version.

**Comment by giangnguyen2412** [comment]
Thank you a lot.
