### ISSUE TITLE
How can I edit config file to run training?

### ISSUE THREAD

**Issue by giangnguyen2412** [ucasir/NPRF#7]
Hi again,

I am running the command for training: ` python nprf_drmm.py --fold 5 1`
Then I am supposing to modify the config file: model/nprf_drmm_config.py, but how can I config this file. I modify the variable `parent_path` to `  parent_path = '/home/dexter/NPRF/model'` (home directory), but it doesn't work.

Could you please help me out.

Thanks.

**Comment by giangnguyen2412** [comment]
This is running log

![Screenshot from 2019-05-15 04-44-17](https://user-images.githubusercontent.com/30857111/57761743-20f76180-76cc-11e9-89ae-fd1b6c161708.png)

**Comment by ucasir** [comment]
Please specify the paths below. It is just the parent path for "os.path.join".

**Comment by giangnguyen2412** [comment]
Hi,

Could you specify which path, I do not understand what should I do now.

**Comment by giangnguyen2412** [comment]
Could you plz help me out?
