### ISSUE TITLE
data link

### ISSUE THREAD

**Issue by wangxinzhe123** [ucasir/NPRF#9]
Hello, could you please give me the download link of the data set?

**Comment by canjiali** [comment]
hey, sorry for the late reply.
you can check the anserini regression notebooks, i.e., [disk12](https://github.com/castorini/anserini/blob/master/docs/regressions-disk12.md), [robust04](https://github.com/castorini/anserini/blob/master/docs/regressions-disk45.md). 
For the robust04 collection, they also have an easy-to-use colab [notebook](https://github.com/castorini/anserini-notebooks/blob/master/pyserini_robust04_demo.ipynb), where you can also find a built index.

**Comment by wangxinzhe123** [comment]
Hi, can you explain in detail what these following files（res_file ，docnolist_file df_file，topic_file）are?I have disk4 and disk5 files and want to process them into corresponding usable files.Thank you very much for your reply！
relevance_params = {'res_file': os.path.join(global_info_path, 'desc.res'),
                      'qrels_file': os.path.join(global_info_path, 'qrels.clueweb09b.txt'),
                      'docnolist_file': os.path.join(global_info_path, 'docnolist'),
                      'output_file': os.path.join(global_info_path, 'relevance.clue.desc.fromres1000.pickle')}
global_info_path = "/home/lcj/data/desc.disk12/features/global.info"
  idf_params = {'df_file': os.path.join(global_info_path, 'disk12.dfcf.txt'),
                'topic_file': os.path.join(global_info_path, 'disk12.desc.porter.morefilter.txt'),
                'output_file': os.path.join(global_info_path, 'desc.idf.pickle'),
                }
